# Generated by Django 3.2.5 on 2022-05-04 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassChar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hp', models.FloatField(default=0)),
                ('describe', models.CharField(max_length=250)),
                ('focus', models.IntegerField(default=1)),
                ('condition', models.IntegerField(default=1)),
                ('min_dmg_physical', models.FloatField(default=1.0)),
                ('max_dmg_physical', models.FloatField(default=2.0)),
                ('min_dmg_magical', models.FloatField(default=0.5)),
                ('max_dmg_magical', models.FloatField(default=0.75)),
                ('self_heal', models.IntegerField(default=5)),
                ('armor', models.IntegerField(default=0)),
                ('charisma', models.IntegerField(default=0)),
                ('thievery', models.IntegerField(default=0)),
                ('stealh', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('wit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hp', models.FloatField(default=0)),
                ('describe', models.CharField(max_length=250)),
                ('focus', models.IntegerField(default=1)),
                ('condition', models.IntegerField(default=1)),
                ('min_dmg_physical', models.FloatField(default=1.0)),
                ('max_dmg_physical', models.FloatField(default=2.0)),
                ('min_dmg_magical', models.FloatField(default=0.5)),
                ('max_dmg_magical', models.FloatField(default=0.75)),
                ('self_heal', models.IntegerField(default=5)),
                ('armor', models.IntegerField(default=0)),
                ('charisma', models.IntegerField(default=0)),
                ('thievery', models.IntegerField(default=0)),
                ('stealh', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('wit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('class_name', models.CharField(max_length=50)),
                ('fraction_name', models.CharField(max_length=50)),
                ('hp', models.FloatField(default=0)),
                ('story', models.CharField(max_length=350)),
                ('focus', models.IntegerField(default=0)),
                ('condition', models.IntegerField(default=0)),
                ('min_dmg_physical', models.FloatField(default=0.0)),
                ('max_dmg_physical', models.FloatField(default=0.0)),
                ('min_dmg_magical', models.FloatField(default=0.0)),
                ('max_dmg_magical', models.FloatField(default=0.0)),
                ('self_heal', models.IntegerField(default=0)),
                ('armor', models.IntegerField(default=0)),
                ('charisma', models.IntegerField(default=0)),
                ('thievery', models.IntegerField(default=0)),
                ('stealh', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('wit', models.IntegerField(default=0)),
                ('char_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotr.player')),
                ('class_key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lotr.classchar')),
                ('fraction_key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lotr.fraction')),
            ],
        ),
    ]
